version: '3.9'

services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/app
    tty: true